---
- hosts: 172.31.33.117
  become: yes
  tasks:
  - name: I want to execute linux command
    command: hostname -f
    register: myfirsttaskresult

  - name: 
    apt:
         name: git
         state: present
         when: myfirsttaskresult.stderr == ""

  - name: 
    apt:
         name: tree
         state: present
         when: myfirsttaskresult.stderr != ""
