---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: I want to install git,tree and wget
    apt:
      name: "{{ item }}"
      state: present
    loop:  
      - git
      - tree
      - wget
