---
- hosts: all
  become: yes
  tasks:
   - name: Install web server on ubuntu server only
     apt:
          name: apache2
          state: present
     when: ansible_os_family == "Debian"
   - name: I want to start webserver on ubuntu server onl
     service:
          name: apache2
          state: started
     when: ansible_os_family == "Debian"

